# examples/module1/chapter6-nav2-fundamentals/nav2_params.yaml

amcl:
  ros__parameters:
    use_sim_time: True
    alpha1: 0.2
    alpha2: 0.2
    # ... other AMCL parameters

bt_navigator:
  ros__parameters:
    use_sim_time: True
    bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

# ... other Nav2 component configurations
